// Elements
// ------------------------------------
var form = document.querySelector("form");
var show = document.querySelector("form .keyword");
var results = document.querySelector(".results");
var tvshowTemplate = document.querySelector("#tvshow-template");
var headerTemplate = document.querySelector("#header-template");

// Event
// ------------------------------------
form.addEventListener('submit', getShowlist);


// Event Handler 
// ------------------------------------
function getShowlist(event) {
	event.preventDefault();

	var search = show.value;
	console.log(search);

	var url = "http://api.themoviedb.org/3/search/tv?api_key=e3dcc070a2e3e601e513b356cbaeaf8a&query=" + search;

	$.getJSON(url, updateShowlist);
}

// Update page
// ------------------------------------
function updateShowlist(json) {
	console.log('updateShowlist',json);

	// clears out the old results
	results.innerHTML = '';

	// add new result for each item in array
//	json.restaurants.forEach(createRestaurant);

	var template = Handlebars.compile(headerTemplate.innerHTML);
	// This is compiling the template source from the <script> tag into a Handlebars template
	var template = Handlebars.compile(tvshowTemplate.innerHTML);

	// technique #1 - one line solution that sets the innerHTML of ul to the li html that was generated by handlebars
//	results.innerHTML = template(json.restaurants);

	// technique #2 - save in variable first
	var html = template(json.results);
	results.innerHTML = html; 

}
/*
function createRestaurant(i) {

	var li = document.createElement("li");

	var template = 
		'<img src="' + i.image_url +'">' +
		'<h2>' + i.name +'</h2>' +
		'<p>' + i.address +'</p>';

	//console.log(template);
	li.innerHTML = template;
	results.appendChild(li);

}
*/
/*
function createRestaurant(restaurant) {

	// Step 1 - create elements
	var li = document.createElement("li");
	var img = document.createElement("img");
	var h2 = document.createElement("h2");
	var p = document.createElement("p");

	// Step 2 - add content / attributes
	img.src = restaurant.image_url;
	h2.textContent = restaurant.name;
	p.textContent = restaurant.address;

	// Step 3 - append to parents
	results.appendChild(li);
	li.appendChild(img);
	li.appendChild(h2);
	li.appendChild(p);
}

*/

	




